/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceUtilisateur;

/**
 *
 * @author Aurélien
 */
public class Accueil extends javax.swing.JPanel {

    /**
     * @return the jTree1
     */
   

    /**
     * @return the jTree2
     */
 

    /**
     * @return the jTree3
     */
 
    /**
     * @return the jTree4


    /**
     * @return the jTree5
     */
    public javax.swing.JTree getjTree5() {
        return null;
        
    }

    /**
     * @return the jTree6
     */

    /**
     * @return the jButton2


    /**
     * @return the jButton6
     */
    

    /**
     * Creates new form Jmenu
     */
    public Accueil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setLayout(null);
        add(jPanel2);
        jPanel2.setBounds(-20, 160, 10, 10);

        jPanel3.setBackground(java.awt.Color.lightGray);
        jPanel3.setLayout(new java.awt.BorderLayout());
        add(jPanel3);
        jPanel3.setBounds(0, 640, 1940, 870);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaceUtilisateur/princeton_plainsboro_by_nadesiko.jpg"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, 0, 648, 648);

        jPanel1.setBackground(java.awt.Color.lightGray);
        add(jPanel1);
        jPanel1.setBounds(640, 0, 1940, 870);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jButton7
     */
    
}
