/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceUtilisateur;

import Listenner.BoutonListenerGen;
import Listenner.BoutonListenerJTreeListe;
import Listenner.BoutonListenerValider;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JTree;
import javax.swing.event.TreeSelectionListener;
import princetonPlainsboro.LectureXML;
import princetonPlainsboro.SIH;

/**
 *
 * @author Aurélien
 */
public class Fen extends javax.swing.JFrame {

    
  
    //Declaration Panel
    ConnexionInterface c = new ConnexionInterface();

    JListeDePatients lp = new JListeDePatients();
     JCreerDP jcdp = new JCreerDP();
     JCoutPatient jcp = new JCoutPatient();
    JListeDeMedecins lm = new JListeDeMedecins();
     JCoutMedecin jcm = new JCoutMedecin();
     JCoutSpecialite1 jcs = new JCoutSpecialite1();
     Accueil a = new Accueil();
     Jmenu jm = new Jmenu();
     JFrame frame=this;
      JConsulterFDS_dans_ongletFDS jfdsdofds = new JConsulterFDS_dans_ongletFDS();
     Barre b = new Barre();
     SIH sih;
     
     //Declaration bouton
    private JButton valider = c.getjButton1();
   
    private State state;
    private JTree jtreeliste = jm.getjTree2();
   
//    /**
//     * Creates new form Fen
//     */JFrame frame = this;

    
        //Declaration JTren
    public Fen() {
        state=State.NONCO;
        add(c);
        this.setSize(950,600);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        valider.addActionListener(new BoutonListenerValider(jm,c,a,b,this));
        LectureXML lecture = new LectureXML("dossiers.xml");
        sih=lecture.getDossier();
        
        jtreeliste.addTreeSelectionListener(new BoutonListenerJTreeListe(lp,jcdp,jcp,lm,jcm,jcs,a,jm,frame,jfdsdofds,sih));
        
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fen().setVisible(true);
                
            }
        });
    }

    /**
     * @param state the state to set
     */
    public void setState(State state) {
        this.state = state;
    }

    /**
     * @param state the state to set
     */
    
    
    
    
    
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

